### ISSUE TITLE
What if we enable it on focus as well?

### ISSUE THREAD

**Issue by giovannipds** [Richard1320/Lava-Lamp#9]
Hello @Richard1320! I was using your script today and I noticed that we aren't enabling it on focus, just on hover, so I checked out the code and came here just to discuss with you what you think about it. Do you agree? Would it be an improvement? If won't have time to do that just let me know, maybe I can help you with that and make you a PR sometime soon, since I am the one who's asking you this. Best wishes to you and thanks for the project. Bye!

**Comment by giovannipds** [comment]
Another interesting update, would be changing the default data active var name to "lavalamp-active", for compatibility purposes.

**Comment by Richard1320** [comment]
Focus never really occurred to me since I always control everything with the mouse. I can see how it might be useful for forms so I added an option to animate on focus and descendant focus. Also changed the name of the active data object to "lavalampActive" so it should be more compatible with other plugins. Thanks for the suggestions.

**Comment by giovannipds** [comment]
:+1: good, I thank you for the attention! My pleasure. Regards, Gio.
